# Site settings
email: xinabner@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: Coconut
description:
url: ""
twitter_username:
default_img:

# Profile settings
name:
profile_img: https://unsplash.it/2000/1200?random
profile: 魔都上海的一个还未入门的程序员， 今年才毕业， 励志造造轮子什么的， Coconut， 闲来写字的地方。
social:
  github: https://github.com/AbnerXin

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
